homeassistant:
  name: DevInstance
  latitude: !
  longitude: !
  elevation: 0
  unit_system: metric

custom_components:
  - pp_reader

logger:
  default: info
  logs:
    custom_components.pp_reader: debug
