# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: portfolio.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fportfolio.proto\x12\tportfolio\"4\n\x0fSerializedModel\x12!\n\x04root\x18\x01 \x01(\x0b\x32\x13.portfolio.RootNode\"-\n\x08RootNode\x12!\n\x06\x63lient\x18\x01 \x01(\x0b\x32\x11.portfolio.Client\"W\n\x06\x43lient\x12\'\n\nsecurities\x18\x01 \x03(\x0b\x32\x13.portfolio.Security\x12$\n\x08\x61\x63\x63ounts\x18\x02 \x03(\x0b\x32\x12.portfolio.Account\"\x82\x01\n\x08Security\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04isin\x18\x02 \x01(\t\x12\x15\n\rticker_symbol\x18\x03 \x01(\t\x12\x10\n\x08\x63urrency\x18\x04 \x01(\t\x12\x15\n\rcurrent_price\x18\x05 \x01(\x01\x12\x0c\n\x04type\x18\x06 \x01(\t\x12\x0c\n\x04uuid\x18\x07 \x01(\t\"H\n\x07\x41\x63\x63ount\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08\x63urrency\x18\x02 \x01(\t\x12\x0f\n\x07\x62\x61lance\x18\x03 \x01(\x01\x12\x0c\n\x04uuid\x18\x04 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'portfolio_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SERIALIZEDMODEL._serialized_start=30
  _SERIALIZEDMODEL._serialized_end=82
  _ROOTNODE._serialized_start=84
  _ROOTNODE._serialized_end=129
  _CLIENT._serialized_start=131
  _CLIENT._serialized_end=218
  _SECURITY._serialized_start=221
  _SECURITY._serialized_end=351
  _ACCOUNT._serialized_start=353
  _ACCOUNT._serialized_end=425
# @@protoc_insertion_point(module_scope)
