You are my coding assistant. I need you to prepare a pull request that merges the current `dev` branch into `main`.

Before running any scripts, perform the following verification steps:
1. Confirm that the integration manifest(s) (e.g., `custom_components/pp_reader/manifest.json`) have their `version` field set to the latest version number that appears in the top entry of `CHANGELOG.md`.
2. If the manifest version and the latest changelog version do not match, report this mismatch, state explicitly that this is a blocking issue, and DO NOT execute any scripts.

If the manifest version matches the latest changelog version, proceed with the release preparation workflow:
1. Check out the `dev` branch (or confirm it is already checked out) and ensure it is up to date.
2. Execute `scripts/prepare_main_pr.sh` so that only the intended content is promoted from `dev` to `main`.
3. Collect all necessary details to describe the PR content, including notable changes, tests, or release notes generated by the script.
4. Draft a concise yet comprehensive PR description summarizing the updates that will move from `dev` to `main`.

After completing the above, provide me with:
- A clear statement confirming whether the manifest version validation passed.
- A summary of the steps performed, explicitly mentioning that `scripts/prepare_main_pr.sh` was executed (or not executed if blocked).
- The finalized PR title and body that I can use for the `dev` to `main` promotion.
