#!/usr/bin/env bash

# Fail on errors and undefined vars
set -euo pipefail

cd "$(dirname "$0")/.."

APT_PACKAGES=(ffmpeg libturbojpeg libpcap-dev libsqlite3-dev python3-venv)
if command -v apt-get >/dev/null; then
    sudo apt-get update -y
    sudo apt-get install -y "${APT_PACKAGES[@]}"
fi

if command -v pyenv >/dev/null; then
    pyenv install -s 3.13.3
    pyenv global 3.13.3
fi

if [ ! -d ".venv" ]; then
    python3 -m venv .venv
fi
source .venv/bin/activate

pip install --upgrade pip
pip install --requirement requirements.txt
pip install --requirement requirements-dev.txt

if [ ! -d "config" ]; then
    mkdir -p "config"
fi

echo "Setup complete. Run ./scripts/develop to start Home Assistant."
