name: Build & Upload HACS ZIP

# Wird ausgelöst, sobald du einen Release publishst
on:
  release:
    types:
      - published

jobs:
  build_zip:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # Erlaubt, Assets an den Release zu hängen

    steps:
      # 1) Checkout des gesamten Repos (inkl. Tags)
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2) ZIP-Package zusammenstellen
      - name: Build ha-pp-reader.zip
        run: |
          # Lege temp-Verzeichnis an
          rm -rf package && mkdir package

          # Kopiere den Integrations­code hinein (Inhalt von custom_components/pp_reader)
          mkdir -p package/custom_components/pp_reader
          cp -r custom_components/pp_reader/. package/custom_components/pp_reader/

          # Kopiere Frontend & Metadaten dazu
          cp -r frontend             package/
          cp hacs.json               package/
          cp README.md               package/
          cp LICENSE                 package/

          # Erzeuge das ZIP ohne weiteren übergeordneten Wrapper
          cd package
          zip -r ../ha-pp-reader.zip ./*
          cd ..

      # 3) ZIP als Asset an den gerade veröffentlichten Release hängen
      - name: Upload ZIP to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ha-pp-reader.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

